// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojmehnhktwazriugfsnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qbWVobmhrdHdhenJpdWdmc251Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzOTg3MjUsImV4cCI6MjA3Mzk3NDcyNX0.n1JOTmnUToX9p7FjIZFCqCPEfAihgCjy7GU1nXrrslc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});